### ISSUE TITLE
Registered routes returning 404

### ISSUE THREAD

**Issue by DrBeak1** [glock45/swifter#381] opened 2019-04-05 23:53 UTC
Having issues potentially related to overlapping routes:
`/user/v1/orders/rating/pending` 
`/user/:id/order/active`
I thought it may be addressed by https://github.com/httpswift/swifter/pull/379 but even after modifying the files with these changes still seeing 404s returned for `/user/v1/orders/rating/pending`.

**Comment by Vkt0r** [comment] 2019-04-07 03:22
@DrBeak1 Thanks for reporting this. I'm afraid this is a duplicate of #376 and after reading more of #378 too!. Your test case was very useful. I'm working on a fix for the issue that would fix the current issues with the routes overlapping.

**Comment by Vkt0r** [comment] 2019-04-07 03:42
@DrBeak1 Can you please point your `Podfile` or `Cartfile` to #382 and give it a try with your current repository and let me know if the issue was fixed?

**Comment by DrBeak1** [comment] 2019-04-08 18:17
@Vkt0r yes this does fix the issue. Thank you very much and sorry for the duplicate.

**Comment by DrBeak1** [comment] 2019-04-08 18:18
fixed by https://github.com/httpswift/swifter/pull/382

**Closed as completed** 2019-04-08 18:17 UTC

**Comment by Vkt0r** [comment] 2019-04-08 18:49
Hey, @DrBeak1 No problem with the duplicate, your case was very helpful to fix the issue, so thanks for it. Glad to know your issue was fixed 😀.

**Comment by AndrewBennet** [comment] 2019-04-22 10:58
Any chance you could release a new version with this fix? I can't use the current Swift 5 release (1.4.6) because of this issue - I've pointed my Podfile to the latest commit on master instead. Thanks!

**Comment by Vkt0r** [comment] 2019-04-22 14:26
Hey @AndrewBennet yes we would try to release a new version soon, but you can always set your `Podfile` to the branch `stable` in the meantime and not to one specific commit.
