### ISSUE TITLE
Is shareFilesFromDirectory Broken?

### ISSUE THREAD

**Issue by flashanand** [glock45/swifter#439] opened 2019-11-12 15:24 UTC
I have this code:

let server = demoServer("/Users/anand/Desktop/")
server["/assets/:path"] = shareFilesFromDirectory("/Users/anand/Desktop/")
try server.start(8081, forceIPv4: true)

and i try to open this page :
http://localhost:8081/assets/webpage.html
I am getting "This localhost page can’t be found" Error

Also http://localhost:8081/ looks like this with an Empty Bullet
<img width="199" alt="Screen Shot 2019-11-12 at 8 44 05 PM" src="https://user-images.githubusercontent.com/3656319/68684100-ecd2ff80-058d-11ea-9549-bf707b27e9ca.png">

I am using it from a Sand Boxed macOS App.

**Comment by antrov** [comment] 2019-11-19 11:22
Indeed, it is. HttpRequest.params dictionary is always empty, as it is set in HttpServerIO.handleConnection() and never filled with parsed URL components.

It will be fixed by project maintainers or it is recommended to create PR on my own?

**Comment by Vkt0r** [comment] 2019-11-19 13:36
@flashanand @antrov There is a discussion about this issue in #420 and #405. @antrov You're more than welcome to create a PR of course, but please read the issues in order to understand how it should work.

**Comment by Vkt0r** [comment] 2019-11-19 13:36
Duplicate of #420.

**Closed as completed by Vkt0r** 2019-11-19 13:36 UTC
