### ISSUE TITLE
Continuous data stream ?

### ISSUE THREAD

**Issue by MrSkwiggs** [glock45/swifter#348] opened 2018-11-04 20:46 UTC
How exactly would I go about streaming some continuous data (i.e from a device capture) ? 
Can I do so with a simple GET or should I use websockets ?

Sorry for the totally noobish question but I'm super lost.

**Comment by Vkt0r** [comment] 2018-11-26 04:51
@TheSkwiggs Maybe #311 can help you!

**Comment by Vkt0r** [comment] 2019-07-18 13:30
Duplicate of #311

**Closed as completed by Vkt0r** 2019-07-18 13:30 UTC
