### ISSUE TITLE
change behavior with 1.4.7

### ISSUE THREAD

**Issue by prasann-1433** [glock45/swifter#417] opened 2019-06-12 23:32 UTC
I am having url path say 
/test/demon/... ?acb=1.0?def=2.0 
 in 1.4.6 we can easily parse this using server[test/:path] and it used to give me request.params[:path] like "/demon/.. "

while in 1.4.7 
same url path doesn't get recognize with server[test/:path] infact i need to give like 
server[test/demon/:path] or server[test/*/:path]. 

Is there a new changes which we need to consume in order to use 
/test/demon/... ?acb=1.0?def=2.0  with simple format server[test/:path] like this and can be 
request.params[:path] will have all values as "demon/...  "

**Comment by Vkt0r** [comment] 2019-06-13 02:16
Duplicate of #405. Please see the mentioned issue and how the behavior has changed.

**Closed as completed** 2019-06-13 02:17 UTC
