### ISSUE TITLE
Same folder and file name

### ISSUE THREAD

**Issue by lu15gv** [glock45/swifter#418] opened 2019-06-21 23:35 UTC
Swifter is not sending back the response in this scenario:

I have this json account file:
`https://.../user/account`

And also, I have an account folder at the same level, that contains other files, like this config file:
`https://.../user/account/config`

The problem is, if I try to stub both responses at the same time:

The second one works but the first one don't
If I stub each one isolated, both work

**Comment by Vkt0r** [comment] 2019-06-24 15:25
Hey, @lu15gv Thanks for reporting this. Can you please share your route declaration?

**Comment by lu15gv** [comment] 2019-06-24 21:25
Sure:
```
server["/course/loyal/user/account/config"] = { _ in
                HttpResponse.ok(.json(jsonData as AnyObject))
            }
```
And
```
server["/course/loyal/user/account"] = { _ in
                HttpResponse.ok(.json(jsonData as AnyObject))
            }
```

**Comment by Vkt0r** [comment] 2019-07-03 22:43
@lu15gv Thanks for sharing the example 👍. I created a test to reproduce the issue with the same routes you mentioned above but I couldn't reproduce it, the test is passing successfully I'm afraid.

```swift
func testHttpRouterHandlesOverlappingPathsWithoutDynamicPath() {

        let request = HttpRequest()

        let firstVariableRouteExpectation = expectation(description: "First Route")
        var foundFirstVariableRoute = false
        router.register("GET", path: "/a/b/c/d/e") { _ in
            foundFirstVariableRoute = true
            firstVariableRouteExpectation.fulfill()
            return HttpResponse.accepted
        }

        let secondVariableRouteExpectation = expectation(description: "Second Route")
        var foundSecondVariableRoute = false
        router.register("GET", path: "/a/b/c/d") { _ in
            foundSecondVariableRoute = true
            secondVariableRouteExpectation.fulfill()
            return HttpResponse.accepted
        }

        let firstRouteResult = router.route("GET", path: "/a/b/c/d/e")
        let firstRouterHandler = firstRouteResult?.1
        XCTAssertNotNil(firstRouteResult)
        _ = firstRouterHandler?(request)

        let secondRouteResult = router.route("GET", path: "/a/b/c/d")
        let secondRouterHandler = secondRouteResult?.1
        XCTAssertNotNil(secondRouteResult)
        _ = secondRouterHandler?(request)

        waitForExpectations(timeout: 10, handler: nil)
        XCTAssertTrue(foundFirstVariableRoute)
        XCTAssertTrue(foundSecondVariableRoute)
    }
```

Can you please give more information about the issue or create a sample project in which I can take a look ? Also can you please tell me wich version of the project are you using ?

**Comment by Vkt0r** [comment] 2019-11-05 04:37
Closing this, please feel free to open if the issue persists.

**Closed as completed by Vkt0r** 2019-11-05 04:37 UTC
