### ISSUE TITLE
releaseAcceptSocket() doesn't cut availability of the server

### ISSUE THREAD

**Issue by RGreinacher** [glock45/swifter#25] opened 2015-06-04 00:02 UTC
The stop() / releaseAcceptSocket() methods don't seem to shut the server down. It is still available after I called the method. Is there a way to shut it completely down or did I misinterpreted the meaning of those?
Thank you!

**Comment by glock45** [comment] 2015-06-09 07:53
I've just tested it using demo iOS app and works fine for me. Anyway, could you please paste the code you use for testing ?

**Comment by RGreinacher** [comment] 2015-06-15 12:39
Sorry for the late answer; I can reproduce the mentioned behavior with the following sample code:
I figured out, that the server doesn't shut down only if there was a request before the `server.stop()` method is called. If you just start it and wait until `stop()` is called without performing a request, the server will behave as expected; the request will be refused.

Run the following twice, once just wait until the `sleep(5)` is over and then try to request the server, and once fire a request within the time of the `sleep(5)` (like `http://localhost:9080`) and try the same after `stop()` was called. The latter will answer twice (or more, it just seems to not release the socket).

	import Foundation
	var error: NSError?
	let server = demoServer(NSBundle.mainBundle().resourcePath)

	if !server.start(listenPort: 9080, error: &error) {
			println("Server start error: \(error)")
	} else {
			println("Server started; try a connection now")
			sleep(5)

			println("main thread is awake again")
			server.stop()

			println("stopped server; try to connect")
			while ( true ) { };
	}

**Comment by glock45** [comment] 2015-06-15 12:48
ok. Thanks. I can reproduce it.

**Comment by glock45** [comment] 2015-06-15 12:58
The problem is a while loop happening in case of "keep-alive" session.

**Comment by RGreinacher** [comment] 2015-06-15 13:02
I see. What do you think of a force-kill-switch like `server.sleep(forceShutdown: Bool)`?

**Comment by glock45** [comment] 2015-06-15 13:04
I would like to extend server::stop() by closing all sockets.

**Comment by glock45** [comment] 2015-06-15 13:42
This solves the problem:

https://github.com/glock45/swifter/commit/b37392bf004ffba0dcce4bf2c8a8e6d03b1024ca

**Comment by RGreinacher** [comment] 2015-06-15 13:50
Great work! Thank you! :)

**Closed** 2015-06-15 14:20 UTC
