### ISSUE TITLE
Routing long and arbitrary paths with wildcard doesn't work in 1.4.3

### ISSUE THREAD

**Issue by killmyrene** [glock45/swifter#409] opened 2019-05-08 16:02 UTC
On 1.3.3 we make use of the swifter to intercept manifest & segment calls from the AVPlayer using the '*/:lasthPath' route. Something like this

server["*/:lastPath"] = { request in
    return something
}

That allows us to proxy paths like /AEG_CP/soemthing/seomtgin/output_mobile_hls.ism/index.m3u8 and /AEG_CP/aomething/otherSomethging/123123123/0123123.ts

On 1.4.3 however it doesn't let us do that anymore. 

Would you be able to address this? If not we'll revert back to 1.3.3 but hav not address swift 5 compiler issues

**Comment by Vkt0r** [comment] 2019-05-11 19:31
Hey, @killmyrene Thanks for reporting this. Your issue is a duplicate of #405, please see my comments about it.

**Comment by Vkt0r** [comment] 2019-05-11 19:32
Duplicate of #405

**Closed as completed** 2019-06-13 02:15 UTC
